### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by michaelachrisco** [freecodecamp-fresnoca/landing-page#1]
# Content
### Navigation
We'll need a way to get to: 
- [ ] [About page](https://github.com/freecodecamp-fresnoca/landing-page/issues/2) 
- [ ] [Event/Blog page](https://github.com/freecodecamp-fresnoca/landing-page/issues/3)
- [ ] Member showcase (let's make an issue for this when we're ready to start working on it)
- [ ] [Guest presenter modal](https://github.com/freecodecamp-fresnoca/landing-page/issues/6)
### Headline / Blurb
- [ ] Headline / Subhead content (I.e., something better than "Welcome to our webpage!")
- [x] Meetup time, location, organizer contact info blurb
- [ ] add to calendar button (Juan is working on this [here](https://github.com/freecodecamp-fresnoca/landing-page/issues/5))
### Embedded map
- [ ] Placeholder for dynamic map / snapshot of the map and link to Google Maps
- [ ] Embedded dynamic map (will replace the placeholder + link)
### Supporting content
- [x] Super brief blurb on what we're about, longer version + a little more on the history of FCC and our Fresno chapter at the [About page](https://github.com/freecodecamp-fresnoca/landing-page/issues/2)
### Footer
Alan has dibs on the footer. :)
- [ ] Links to main Free Code Camp site, our Facebook, our Github, should we get a Twitter account?
- [ ] Redundant Nav links including guest presenter modal
- [ ] A simple JavaScript game? 
#### (can be organized into the right spot later, leave it here for now)  
- [ ] freeCodeCamp logo (in SVG format if possible). 
- [ ] placeholder for pages not ready yet (someone want to make a sweet CSS image and witty one liner for this?)
- [x] Basic site architecture (how pages link to one another)

----
# Styling
### Navigation
How do you know which page in the nav you are on?
- [ ] Styling of the current page in the nav
- [ ] Styling of the other pages you can visit in the nav
### Color palette / Theme
- [x] Dark theme? (maybe a toggle at some point to show mad CSS skills between dark, light, space cats, etc)
- [ ] Overall color scheme (post hex numbers or RGB specs here:)
### Mobile considerations
Decide on what mobile configurations we want to support:
- [ ] Current Android/iOS versions

Android/iOS versions that are still widely used from a few years ago:
- [ ] Android ...
- [ ] iOS ...
### Fonts
- [ ] List or link them here, but explain why they might be a good fit for the project
- [ ] Decide on fonts to use
### Layouts
- [x] Mobile layout draft
- [ ] Desktop draft
### Extras that would be cool to put on the home/landing page
- [ ] Easter egg layout for wide screens?
- [x] Custom background pattern? (Fresno icon + code?)
- [ ] CSS animations for dynamic actions (loading, transitions to a menu/modal) that help the user understand what is happening on the page

**Comment by ThomastheBicyclist** [comment]
### Super brief blurb on what we're about \[Draft\]:

Free Code Camp is a global organization to teach real-world coding skills and this is the Fresno chapter website. All that is needed to join our meet up group is a sincere motivation to learn or teach code and a computer that can connect to wifi. We recommend registering an account at freecodecamp.com and doing a few exercises first, but that's not required.

----
### Comments / Suggestions
#### Feel free to edit the blurb directly or leave comments here:
- Feels a little dry, could add some flavor/humor?

**Comment by ThomastheBicyclist** [comment]
### Site architecture
```
                 Home or Landing Page
                      /    |    \
                     /     |     \
                 About     |     Event or Blog
                           |
                   Member Showcase
                           /\
                          /  \
                  Featured    List of member pages, search
                                        /\
                                       /  \
                                 Member    Placeholder or
                                  page       what I'm working
                                                on page
```
----
#### Comments / Suggestions

**Comment by ThomastheBicyclist** [comment]
### Meetup time, location, organizer contact info blurb
We meet on the first Saturday of the month at Root Access Hackerspace from 1pm to 3pm. 

----
#### Comments / Suggestions:
